# Generated by Django 4.2.7 on 2023-11-10 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("runner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceregistration",
            name="crew",
            field=models.ManyToManyField(
                related_name="crew_races", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="raceregistration",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="races",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
