# Generated by Django 4.2.7 on 2023-11-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0002_alter_raceregistration_crew_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidstation",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stations",
                to="runner.race",
            ),
        ),
    ]
